Update 04.blazor-pull-request.yml

diff --git a/.github/workflows/04.blazor-pull-request.yml b/.github/workflows/04.blazor-pull-request.yml
--- a/.github/workflows/04.blazor-pull-request.yml
+++ b/.github/workflows/04.blazor-pull-request.yml
@@ -17,9 +17,6 @@ jobs:
       checks: write
     
     steps:
-      
-      # - name: Make PR Fail
-      #  run: exit 1
 
       - uses: actions/checkout@v4
 
@@ -63,20 +60,20 @@ jobs:
         run: |
           dotnet test "${{ github.workspace }}/blazorapp/BlazorApp.sln" --no-restore --verbosity normal  --logger "trx;LogFileName=test-results.trx"
 
-#       UNCOMMENT TO SHOW CUSTOM ACTIONS
-      - name: Test Report
-        uses: dorny/test-reporter@v1.7.0
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: XUnit Tests            # Name of the check run which will be created
-          path: ${{ github.workspace }}/blazorapp/tests/UnitTests/TestResults/*.trx    # Path to test results
-          reporter: dotnet-trx
+# #       UNCOMMENT TO SHOW CUSTOM ACTIONS
+#       - name: Test Report
+#         uses: dorny/test-reporter@v1.7.0
+#         if: success() || failure()    # run this step even if previous step failed
+#         with:
+#           name: XUnit Tests            # Name of the check run which will be created
+#           path: ${{ github.workspace }}/blazorapp/tests/UnitTests/TestResults/*.trx    # Path to test results
+#           reporter: dotnet-trx
 
-      - name: Label PR based on criteria
-        id: labeler
-        uses: dmitrycx/labeler@v1.0.0
-        with:
-          github-token: ${{ secrets.GH_TOKEN }}  # Use the secret as the input
+#       - name: Label PR based on criteria
+#         id: labeler
+#         uses: dmitrycx/labeler@v1.0.0
+#         with:
+#           github-token: ${{ secrets.GH_TOKEN }}  # Use the secret as the input
 #        
       - name: Publish
         run: |
