Update 04.blazor-pull-request.yml

diff --git a/.github/workflows/04.blazor-pull-request.yml b/.github/workflows/04.blazor-pull-request.yml
--- a/.github/workflows/04.blazor-pull-request.yml
+++ b/.github/workflows/04.blazor-pull-request.yml
@@ -28,32 +28,32 @@ jobs:
         with:
           dotnet-version: 8.0.x
 
-#      - name: Install dependencies
-#        run: dotnet restore "${{ github.workspace }}/blazorapp/BlazorApp.sln"
+      - name: Install dependencies
+        run: dotnet restore "${{ github.workspace }}/blazorapp/BlazorApp.sln"
       
       
       #       UNCOMMENT TO SHOW CACHING
-      - name: Restore NuGet packages
-        id: cache-nuget
-        uses: actions/cache@v3.3.2
-        with:
-          path: |
-            ${{ github.workspace }}/blazorapp/.nuget
-            ${{ github.workspace }}/blazorapp/**/obj
-            ${{ github.workspace }}/blazorapp/**/bin
-          key: ${{ runner.os }}-nuget-cache-${{ hashFiles('**/*.csproj') }}
-          restore-keys: |
-            ${{ runner.os }}-nuget-cache-${{ hashFiles('**/*.csproj') }}
-            ${{ runner.os }}-nuget-cache-
+      # - name: Restore NuGet packages
+      #   id: cache-nuget
+      #   uses: actions/cache@v3.3.2
+      #   with:
+      #     path: |
+      #       ${{ github.workspace }}/blazorapp/.nuget
+      #       ${{ github.workspace }}/blazorapp/**/obj
+      #       ${{ github.workspace }}/blazorapp/**/bin
+      #     key: ${{ runner.os }}-nuget-cache-${{ hashFiles('**/*.csproj') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-nuget-cache-${{ hashFiles('**/*.csproj') }}
+      #       ${{ runner.os }}-nuget-cache-
 
-      - name: Debug Cache
-        run: |
-          echo "Cache hit: ${{ steps.cache-nuget.outputs.cache-hit }}"
-          ls -R ${{ github.workspace }}/blazorapp
+      # - name: Debug Cache
+      #   run: |
+      #     echo "Cache hit: ${{ steps.cache-nuget.outputs.cache-hit }}"
+      #     ls -R ${{ github.workspace }}/blazorapp
 
-      - name: Install dependencies
-        run: |
-          dotnet restore "${{ github.workspace }}/blazorapp/BlazorApp.sln" --packages .nuget --verbosity normal
+      # - name: Install dependencies
+      #   run: |
+      #     dotnet restore "${{ github.workspace }}/blazorapp/BlazorApp.sln" --packages .nuget --verbosity normal
       #        
 
       - name: Build
@@ -64,19 +64,19 @@ jobs:
           dotnet test "${{ github.workspace }}/blazorapp/BlazorApp.sln" --no-restore --verbosity normal  --logger "trx;LogFileName=test-results.trx"
 
 #       UNCOMMENT TO SHOW CUSTOM ACTIONS
-      - name: Test Report
-        uses: dorny/test-reporter@v1.7.0
-        if: success() || failure()    # run this step even if previous step failed
-        with:
-          name: XUnit Tests            # Name of the check run which will be created
-          path: ${{ github.workspace }}/blazorapp/tests/UnitTests/TestResults/*.trx    # Path to test results
-          reporter: dotnet-trx
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1.7.0
+      #   if: success() || failure()    # run this step even if previous step failed
+      #   with:
+      #     name: XUnit Tests            # Name of the check run which will be created
+      #     path: ${{ github.workspace }}/blazorapp/tests/UnitTests/TestResults/*.trx    # Path to test results
+      #     reporter: dotnet-trx
 
-      - name: Label PR based on criteria
-        id: labeler
-        uses: dmitrycx/labeler@v1.0.0
-        with:
-          github-token: ${{ secrets.GH_TOKEN }}  # Use the secret as the input
+      # - name: Label PR based on criteria
+      #   id: labeler
+      #   uses: dmitrycx/labeler@v1.0.0
+      #   with:
+      #     github-token: ${{ secrets.GH_TOKEN }}  # Use the secret as the input
 #        
       - name: Publish
         run: |
