uncomment testing and labeler

diff --git a/.github/workflows/05.webapi-pull-request.yml b/.github/workflows/05.webapi-pull-request.yml
--- a/.github/workflows/05.webapi-pull-request.yml
+++ b/.github/workflows/05.webapi-pull-request.yml
@@ -39,24 +39,19 @@ jobs:
           dotnet test "${{ github.workspace }}/PublicApi.sln" --no-restore --verbosity normal  --logger "trx;LogFileName=test-results.trx"
 
 #       UNCOMMENT TO SHOW CUSTOM ACTIONS
-#      - name: Test Report
-#        uses: dorny/test-reporter@v1.7.0
-#        if: success() || failure()    # run this step even if previous step failed
-#        with:
-#          name: XUnit Tests            # Name of the check run which will be created
-#          path: ${{ github.workspace }}/tests/UnitTests/TestResults/*.trx    # Path to test results
-#          reporter: dotnet-trx
+      - name: Test Report
+        uses: dorny/test-reporter@v1.7.0
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: XUnit Tests            # Name of the check run which will be created
+          path: ${{ github.workspace }}/tests/UnitTests/TestResults/*.trx    # Path to test results
+          reporter: dotnet-trx
 
       - name: Label PR based on criteria
         id: labeler
         uses: dmitrycx/labeler@v1.0.0
         with:
           github-token: ${{ secrets.GH_TOKEN }}  # Use the secret as the input
-      - name: debug 
-        run: |
-          echo random-number ${{ steps.labeler.outputs.PR_NUMBER }}
-          echo random-number ${{ steps.labeler.outputs.PR_TITLE }}
-          echo random-number ${{ steps.labeler.outputs.PR_BODY }}
         
       - name: Publish
         run: |
